development:
  adapter: postgresql
  encoding: unicode
  database: betz_development
  pool: 5
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: betz_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: betz_production
  pool: 5

